name: Cleanup Deployments

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 列出 Deployments
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/deployments | jq

      - name: 刪除所有 Deployments
        run: |
          DEPLOYMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                             -H "Accept: application/vnd.github+json" \
                             https://api.github.com/repos/${{ github.repository }}/deployments | jq -r '.[].id')

          for ID in $DEPLOYMENTS; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github+json" \
                 https://api.github.com/repos/${{ github.repository }}/deployments/$ID
          done